version: '2'
services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0.2
    volumes:
      - ~/volumes/dating/documents/mongodb/:/data/db/
    networks:
      - dating-frontend-prod
networks:
  dating-frontend-prod:
