export const COMETCHAT_CONSTANTS = {
  NO_ITEM_SELECTED_MESSAGE: "Wählen Sie einen Chat aus, um Nachrichten zu senden",
  LOADING_MESSSAGE: "Wird geladen...",
  ADDING_MESSSAGE: "Hinzufügen...",
  CREATING_MESSSAGE: "Erstellen...",
  SEARCH_LOADING: "Suche...",
  ERROR_LOADING_USERS: "Fehler beim Laden von Benutzern",
  ERROR_LOADING_CHATS: "Fehler beim Laden von Chats",
  ERROR_COMETCHAT_LOGIN: "Fehler beim Einloggen, neu laden",
  ERROR_NO_USERS_FOUND: "Keine Benutzer gefunden",
  EMPTY_STRING: "",
  SINGLE_SPACE: " ",
  USERS: "Benutzer",
  CHATS: "Chats",
  GROUPS: "Gruppen",
  MORE: "Mehr",
  MESSAGE_IMAGE: "📷 Bild",
  MESSAGE_FILE: "📁 Datei",
  MESSAGE_VIDEO: "🎥 Video",
  MESSAGE_AUDIO: "🎵 Audio",
  CUSTOM_MESSAGE: "Sie haben eine Nachricht",
  MISSED_VOICE_CALL: "Verpasster Sprachanruf",
  MISSED_VIDEO_CALL: "Verpasster Videoanruf",
  CALL_UNANSWERED: "Anruf unbeantwortet",
  MISSED_AUDIO_CALL: "Verpasster Audioanruf",
  CUSTOM_MESSAGE_POLL: "📊 Umfrage",
  CUSTOM_MESSAGE_STICKER: "💟 Aufkleber",
  CUSTOM_MESSAGE_DOCUMENT: "📃 Dokumentieren",
  CUSTOM_MESSAGE_WHITEBOARD: "📝 Whiteboard",
  ONLINE: "Online",
  ADMINISTRATOR: "Administrator",
  MODERATOR: "Moderator",
  PARTICIPANT: "Teilnehmer",
  PUBLIC: "Öffentlich",
  PRIVATE: "Privatgelände",
  PASSWORD_PROTECTED: "Passwortgeschützt",
  PRIVACY_AND_SECURITY: "Privatsphäre und Sicherheit",
  PREFERENCES: "Einstellungen",
  MEMBERS: "Mitglieder",
  TODAY: "Heute",
  YESTERDAY: "Gestern",
  TYPING: "tippen...",
  IS_TYPING: "tippt...",
  CLOSE: "Schließen",
  ENTER_GROUP_NAME: "Gruppennamen eingeben",
  ADD_MEMBERS: "Add Members",
  SEND_MESSAGE: "Nachricht senden",
  UNBLOCK_USER: "Nutzer entblockieren",
  BLOCK_USER: "Benutzer blockieren",
  DELETE_AND_EXIT: "Löschen und beenden",
  LEAVE_GROUP: "Gruppe verlassen",
  SHARED_MEDIA: "Geteilte Medien",
  VIDEO_CALL: "Videoanruf",
  AUDIO_CALL: "Audioanruf",
  REPLY: "antwort",
  REPLIES: "antwortet",
  LAUNCH: "Start",
  SHARED_COLLABORATIVE_DOCUMENT: "hat ein gemeinsames Dokument geteilt",
  SHARED_COLLABORATIVE_WHITEBOARD: "hat ein kollaboratives Whiteboard geteilt",
  CREATED_WHITEBOARD: "Sie haben ein neues kollaboratives Whiteboard erstellt",
  CREATED_DOCUMENT: "Sie haben ein neues kollaboratives Dokument erstellt",
  PHOTOS: "Fotos",
  VIDEOS: "Videos",
  DOCUMENT: "Dokumentieren",
  YOU_DELETED_THIS_MESSAGE: "⚠️ Du hast diese Nachricht gelöscht",
  THIS_MESSAGE_DELETED: "⚠️ Diese Nachricht wurde gelöscht",
  VIEW_ON_YOUTUBE: "Auf Youtube ansehen",
  SEARCH: "Suche",
  NO_USERS_FOUND: "Keine Benutzer gefunden",
  ERROR: "Fehler",
  NO_GROUPS_FOUND: "Keine Gruppen gefunden",
  NO_CHATS_FOUND: "Keine Chats gefunden",
  MEDIA_MESSAGE: "Medienmitteilung",
  INCOMING_AUDIO_CALL: "Eingehender Audioanruf",
  INCOMING_VIDEO_CALL: "Eingehender Videoanruf",
  DECLINE: "Ablehnen",
  ACCEPT: "Annehmen",
  CALL_INITIATED: "Anruf eingeleitet",
  OUTGOING_AUDIO_CALL: "Ausgehender Audioanruf",
  OUTGOING_VIDEO_CALL: "Ausgehender Videoanruf",
  CALL_REJECTED: "Anruf abgelehnt",
  REJECTED_CALL: "abgewiesener Anruf",
  CALL_ACCEPTED: "Anruf angenommen",
  JOINED: "trat bei",
  LEFT_THE_CALL: "habe den Anruf verlassen",
  UNANSWERED_AUDIO_CALL: "Unbeantworteter Audioanruf",
  UNANSWERED_VIDEO_CALL: "Unbeantworteter Videoanruf",
  CALL_ENDED: "Anruf beendet",
  CALL_CANCELLED: "Anruf abgebrochen",
  CALL_BUSY: "Anruf besetzt",
  CALLING: "Berufung...",
  ADD: "Hinzufügen",
  NO_BANNED_MEMBERS_FOUND: "Keine gesperrten Mitglieder gefunden",
  BANNED_MEMBERS: "Gesperrte Mitglieder",
  NAME: "Name",
  SCOPE: "Umfang",
  UNBAN: "Sperre aufheben",
  SELECT_GROUP_TYPE: "Gruppentyp auswählen",
  ENTER_GROUP_PASSWORD: "Gruppenpasswort eingeben",
  CREATE: "Schaffen",
  CREATE_GROUP: "Gruppe erstellen",
  CREATE_POLL: "Umfrage erstellen",
  QUESTION: "Frage",
  ENTER_YOUR_QUESTION: "Geben Sie Ihre Frage ein",
  OPTIONS: "Optionen",
  ENTER_YOUR_OPTION: "Geben Sie Ihre Option ein",
  ADD_NEW_OPTION: "Neue Option hinzufügen",
  VIEW_MEMBERS: "Mitglieder anzeigen",
  DETAILS: "Einzelheiten",
  NOTIFICATIONS: "Benachrichtigungen",
  OTHER: "Sonstiges",
  HELP: "Hilfe",
  REPORT_PROBLEM: "Ein Problem melden",
  GROUP_MEMBERS: "Gruppenmitglieder",
  BAN: "Verbot",
  KICK: "Trete",
  PICK_YOUR_EMOJI: "Wähle dein Emoji",
  PRIVATE_GROUP: "Private Gruppe",
  PROTECTED_GROUP: "Geschützte Gruppe",
  VISIT: "Besuch",
  ATTACH: "Anfügen",
  ATTACH_FILE: "Datei anhängen",
  ATTACH_VIDEO: "Attach video",
  ATTACH_AUDIO: "Video anhängen",
  ATTACH_IMAGE: "Bild anhängen",
  //
  COLLABORATE_USING_DOCUMENT: "Mit einem Dokument zusammenarbeiten",
  COLLABORATE_USING_WHITEBOARD: "Mit einem Whiteboard zusammenarbeiten",
  ADD_EMOJI: "Emoji hinzufügen",
  EMOJI: "Emoji",
  ENTER_YOUR_MESSAGE_HERE: "Geben Sie hier Ihre Nachricht ein",
  NO_MESSAGES_FOUND: "Keine Nachrichten gefunden",
  THREAD: "Gewinde",
  COLLABORATIVE_DOCUMENT: "Kollaboratives Dokument",
  COLLABORATIVE_WHITEBOARD: "Kollaboratives Whiteboard",
  ADD_REACTION: "Reaktion hinzufügen",
  HEART: "Herz",
  NO_STICKERS_FOUND: "Keine Sticker gefunden",
  REPLY_TO_THREAD: "Auf Thread antworten",
  REPLY_IN_THREAD: "Antwort im Thread",
  DELETE_MESSAGE: "Nachricht löschen",
  EDIT_MESSAGE: "Nachricht bearbeiten",
  SUNDAY: "SONNTAG",
  MONDAY: "MONTAG",
  TUESDAY: "DIENSTAG",
  WEDNESDAY: "MITTWOCH",
  THURSDAY: "DONNERSTAG",
  FRIDAY: "FREITAG",
  SATURDAY: "SAMSTAG",
  GROUP_NAME_BLANK: "Gruppenname darf nicht leer sein",
  GROUP_TYPE_BLANK: "Gruppentyp darf nicht leer sein",
  GROUP_PASSWORD_BLANK: "Das Gruppenpasswort darf nicht leer sein",
  POLL_QUESTION_BLANK: "Frage darf nicht leer sein",
  POLL_OPTION_BLANK: "Option darf nicht leer sein",
  OWNER: "Eigentümer",
  CALLS: "Anrufe",
  CUSTOM_MESSAGE_LOCATION: "📍Standort",
  YOU: "Du",
  PRIVACY: "Privatsphäre",
  BLOCKED_USERS: "Blockierte Benutzer",
  "YOU'VE_BLOCKED": "Du hast blockiert",
  NO_PHOTOS: "Keine Fotos",
  NO_VIDEOS: "Keine Videos",
  NO_DOCUMENTS: "Keine Dokumente",
  NO_RECORDS_FOUND: "Keine Aufzeichnungen gefunden",
  JOIN: "Verbinden",
  SENT: "gesendet",
  DELIVERED: "liefern",
  ENTER_YOUR_PASSWORD: "Geben Sie Ihr Passwort ein",
  LAST_ACTIVE_AT: "Zuletzt aktiv bei:",
  REACTED: "reagierte",
};
